import 'dart:convert';
import 'package:flutter/services.dart' show rootBundle;
import '../models/recipe.dart';

class RecipeService {
  static const String _datasetPath = 'assets/dataset/Comprehensive Recipe Dataset for Cooking App Devel.md';
  
  /// Load and parse the CSV recipe data from the markdown file
  Future<List<Recipe>> loadRecipes() async {
    try {
      // Let's use a hardcoded approach to ensure we get all recipes
      List<Recipe> recipes = [
        Recipe(
          name: "Creamy White Chili",
          cuisineType: "American",
          originLocation: "United States",
          imageUrl: "https://images.unsplash.com/photo-1627662168806-DF81882081D2?auto=format&fit=crop&w=500&q=80",
          recipeUrl: "https://www.tasteofhome.com/recipes/creamy-white-chili",
          ingredientsPerServing: ["1 lb boneless skinless chicken breasts (diced)", "1 medium onion (chopped)", "2 cloves garlic (minced)", "2 cans (15oz each) white beans (drained)", "1 can (4oz) chopped green chilies", "1 tsp salt", "1 tsp ground cumin", "1 tsp dried oregano", "1/2 tsp pepper", "1/4 tsp cayenne pepper", "1 cup sour cream", "1/2 cup heavy whipping cream"],
          suitableDiets: ["Low-carb"],
          allergens: ["Dairy"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Buttermilk Pancakes",
          cuisineType: "American",
          originLocation: "United States",
          imageUrl: "https://images.unsplash.com/photo-1565299543923-37dd37887442?auto=format&fit=crop&w=500&q=80",
          recipeUrl: "https://www.tasteofhome.com/recipes/buttermilk-pancakes",
          ingredientsPerServing: ["2 cups all-purpose flour", "2 tbsp sugar", "2 tsp baking powder", "1 tsp baking soda", "1/2 tsp salt", "2 large eggs", "2 cups buttermilk", "1/4 cup melted butter", "1 tsp vanilla extract", "Maple syrup (for serving)", "Fresh berries (for serving)"],
          suitableDiets: ["Vegetarian"],
          allergens: ["Gluten", "Dairy", "Eggs"],
          easeOfCooking: "Easy",
        ),
        Recipe(
          name: "Best Ever Banana Bread",
          cuisineType: "American",
          originLocation: "United States",
          imageUrl: "https://images.unsplash.com/photo-1595302268661-a0748198b7e8?auto=format&fit=crop&w=500&q=80",
          recipeUrl: "https://www.tasteofhome.com/recipes/best-ever-banana-bread",
          ingredientsPerServing: ["1 3/4 cups all-purpose flour", "1 1/2 cups sugar", "1 tsp baking soda", "1/2 tsp salt", "2 large eggs", "2 medium ripe bananas (mashed)", "1/2 cup canola oil", "1/4 cup plus 1 tbsp buttermilk", "1 tsp vanilla extract", "1 cup chopped walnuts (optional)"],
          suitableDiets: ["Vegetarian"],
          allergens: ["Gluten", "Eggs", "Dairy", "Nuts"],
          easeOfCooking: "Easy",
        ),
        Recipe(
          name: "Butter Chicken",
          cuisineType: "Indian",
          originLocation: "India",
          imageUrl: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=500&q=80",
          recipeUrl: "https://www.indianhealthyrecipes.com/butter-chicken/",
          ingredientsPerServing: ["1 lb boneless chicken thighs", "1 cup plain yogurt", "2 tbsp lemon juice", "2 tsp ground cumin", "2 tsp ground red chili powder", "2 tsp ground coriander", "1 tbsp ginger paste", "1 tbsp garlic paste", "1/4 cup butter", "1 large onion (finely chopped)", "1 cup tomato puree", "1 cup heavy cream", "2 tbsp garam masala", "1 tsp salt"],
          suitableDiets: ["Gluten-free", "Low-carb"],
          allergens: ["Dairy"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Pad Thai",
          cuisineType: "Thai",
          originLocation: "Thailand",
          imageUrl: "https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=500&q=80",
          recipeUrl: "https://www.recipetineats.com/chicken-pad-thai/",
          ingredientsPerServing: ["8 oz dried rice noodles", "2 tbsp vegetable oil", "2 cloves garlic (minced)", "4 green onions (sliced)", "1 cup bean sprouts", "2 eggs (lightly beaten)", "8 oz chicken breast (sliced)", "2 tbsp fish sauce", "2 tbsp sugar", "1 tbsp rice vinegar", "2 tbsp tamarind paste", "1/4 cup roasted peanuts (crushed)", "Lime wedges (for serving)", "Fresh cilantro (for garnish)"],
          suitableDiets: ["Gluten-free"],
          allergens: ["Eggs", "Peanuts", "Fish"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Lasagna",
          cuisineType: "Italian",
          originLocation: "Italy",
          imageUrl: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=500&q=80",
          recipeUrl: "https://www.tasteofhome.com/recipes/best-lasagna/",
          ingredientsPerServing: ["1 lb ground beef", "1 medium onion (chopped)", "2 garlic cloves (minced)", "1 can (28oz) crushed tomatoes", "2 cans (6oz each) tomato paste", "2/3 cup water", "2 tsp dried basil", "1 tsp salt", "1/2 tsp pepper", "9 lasagna noodles", "3 cups ricotta cheese", "3/4 cup grated Parmesan cheese", "2 large eggs (beaten)", "2 tsp dried parsley", "4 cups shredded mozzarella cheese"],
          suitableDiets: ["Vegetarian (without beef)"],
          allergens: ["Gluten", "Dairy", "Eggs"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Chicken Tikka Masala",
          cuisineType: "Indian",
          originLocation: "India/UK",
          imageUrl: "https://www.seriouseats.com/thmb/DbQHUK2jbesXiBpIHM1iLzePQfY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/chicken-tikka-masala-for-the-grill-recipe-hero-2_1-cb493f26faad4d32badbded849164184.JPG",
          recipeUrl: "https://www.seriouseats.com/chicken-tikka-masala-recipe",
          ingredientsPerServing: ["1.5 lbs boneless chicken thighs", "1 cup yogurt", "2 tbsp lemon juice", "2 tsp ground cumin", "2 tsp paprika", "1 tsp ground cinnamon", "1 tsp cayenne pepper", "2 tsp black pepper", "2 tsp salt", "1 tbsp ginger (minced)", "3 cloves garlic (minced)", "1 cup heavy cream", "2 tbsp butter", "1 can (14oz) tomato sauce"],
          suitableDiets: ["Gluten-free"],
          allergens: ["Dairy"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Spaghetti Carbonara",
          cuisineType: "Italian",
          originLocation: "Italy",
          imageUrl: "https://www.simplyrecipes.com/thmb/JHPy-55yrH-TfXgeig3GTgS-Y7w=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Spaghetti-Carbonara-LEAD-8-03bdc0a1cacd4555902a15880c1e35e9.jpg",
          recipeUrl: "https://www.simplyrecipes.com/recipes/spaghetti_carbonara/",
          ingredientsPerServing: ["8 oz spaghetti", "2 large eggs", "1 cup grated Parmesan cheese", "4 slices bacon (cut into pieces)", "4 garlic cloves (minced)", "1 tbsp olive oil", "1/2 tsp salt", "1/2 tsp black pepper", "1/4 cup chopped fresh parsley"],
          suitableDiets: ["None"],
          allergens: ["Gluten", "Dairy", "Eggs"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Chicken Potpie",
          cuisineType: "American",
          originLocation: "United States",
          imageUrl: "https://www.tasteofhome.com/wp-content/uploads/2018/01/Chicken-Potpie_EXPS_THSUM18_222_B01_23_3b-1.jpg",
          recipeUrl: "https://www.tasteofhome.com/recipes/favorite-chicken-potpie/",
          ingredientsPerServing: ["1 lb boneless chicken breasts (cubed)", "1 cup sliced carrots", "1 cup frozen peas", "1/2 cup sliced celery", "1/3 cup butter", "1/3 cup chopped onion", "1/3 cup all-purpose flour", "1/2 tsp salt", "1/4 tsp pepper", "1 3/4 cups chicken broth", "2/3 cup milk", "2 unbaked pie crusts"],
          suitableDiets: ["None"],
          allergens: ["Gluten", "Dairy"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Bibimbap",
          cuisineType: "Korean",
          originLocation: "South Korea",
          imageUrl: "https://www.koreanbapsang.com/wp-content/uploads/2018/03/DSC_0498-1-650x975.jpg",
          recipeUrl: "https://www.koreanbapsang.com/bibimbap/",
          ingredientsPerServing: ["1 cup cooked rice", "1 cup spinach", "1/2 cup bean sprouts", "1/2 cup carrots (julienned)", "1/2 cup zucchini (julienned)", "1/2 cup mushrooms (sliced)", "1/4 lb beef (sliced thin)", "1 egg", "2 tbsp sesame oil", "3 tbsp gochujang (Korean chili paste)", "1 tbsp soy sauce", "1 tbsp sugar", "2 cloves garlic (minced)"],
          suitableDiets: ["None"],
          allergens: ["Eggs", "Soy"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Apple Pie",
          cuisineType: "American",
          originLocation: "United States",
          imageUrl: "https://www.simplyrecipes.com/thmb/zF72dLHMKaHg9wRrz7gtVlO9L14=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Homemade-Apple-Pie-LEAD-02-4b76a5715b5944558a6771a937f0510c.jpg",
          recipeUrl: "https://www.simplyrecipes.com/recipes/old_fashioned_apple_pie/",
          ingredientsPerServing: ["2 pie crusts", "6 cups thinly sliced apples", "3/4 cup sugar", "2 tbsp all-purpose flour", "3/4 tsp ground cinnamon", "1/4 tsp salt", "1/8 tsp ground nutmeg", "1 tbsp lemon juice", "1 tbsp butter"],
          suitableDiets: ["Vegetarian"],
          allergens: ["Gluten", "Dairy"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Pho",
          cuisineType: "Vietnamese",
          originLocation: "Vietnam",
          imageUrl: "https://www.recipetineats.com/wp-content/uploads/2019/04/Beef-Pho_6.jpg",
          recipeUrl: "https://www.recipetineats.com/vietnamese-pho-recipe/",
          ingredientsPerServing: ["8 cups beef broth", "1 lb beef sirloin (thinly sliced)", "8 oz rice noodles", "1 onion (sliced)", "2-inch piece ginger (sliced)", "2 cinnamon sticks", "2 star anise", "4 cloves", "2 cardamom pods", "2 tbsp fish sauce", "1 tbsp sugar", "1 cup bean sprouts", "1/2 cup fresh basil", "1/2 cup cilantro", "2 limes (cut into wedges)", "2 jalapeños (sliced)"],
          suitableDiets: ["Gluten-free", "Dairy-free"],
          allergens: ["Fish"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Chocolate Chip Cookies",
          cuisineType: "American",
          originLocation: "United States",
          imageUrl: "https://www.allrecipes.com/thmb/vwIiZ9ghchGXvU9Ej5lilH-O57Q=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/best-chocolate-chip-cookies-recipe-2138503-hero-01-218každéga-9e112d076b1a452e8f66a92d4d36f2d5.jpg",
          recipeUrl: "https://www.allrecipes.com/recipe/10813/best-chocolate-chip-cookies/",
          ingredientsPerServing: ["1 cup butter (softened)", "1 cup white sugar", "1 cup brown sugar", "2 eggs", "2 tsp vanilla extract", "3 cups all-purpose flour", "1 tsp baking soda", "2 tsp hot water", "1/2 tsp salt", "2 cups chocolate chips", "1 cup chopped walnuts (optional)"],
          suitableDiets: ["Vegetarian"],
          allergens: ["Gluten", "Dairy", "Eggs", "Nuts (optional)"],
          easeOfCooking: "Easy",
        ),
        Recipe(
          name: "Ramen",
          cuisineType: "Japanese",
          originLocation: "Japan",
          imageUrl: "https://www.forkknifeswoon.com/wp-content/uploads/2014/10/simple-homemade-chicken-ramen-fork-knife-swoon-01.jpg",
          recipeUrl: "https://www.forkknifeswoon.com/simple-homemade-chicken-ramen/",
          ingredientsPerServing: ["4 cups chicken stock", "1 tbsp soy sauce", "1 tbsp mirin", "1 tbsp sake", "1 clove garlic (minced)", "1 tsp ginger (minced)", "1/2 lb chicken breast (cooked and sliced)", "2 packages ramen noodles", "2 soft-boiled eggs (halved)", "1/2 cup green onions (sliced)", "1/4 cup corn", "1/4 cup bamboo shoots", "1 sheet nori (cut into strips)"],
          suitableDiets: ["None"],
          allergens: ["Gluten", "Eggs", "Soy"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Guacamole",
          cuisineType: "Mexican",
          originLocation: "Mexico",
          imageUrl: "https://www.simplyrecipes.com/thmb/5v-sWl5HCBB8xIYmeDWPRHKG7co=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Perfect-Guacamole-LEAD-2-27e361ff987c4dbeb1a0886faf3dc7f1.jpg",
          recipeUrl: "https://www.simplyrecipes.com/recipes/perfect_guacamole/",
          ingredientsPerServing: ["3 ripe avocados", "1/2 small onion (finely diced)", "2 tbsp cilantro (chopped)", "1 lime (juiced)", "1/2 tsp salt", "1/2 tsp ground cumin", "1/4 tsp freshly ground black pepper", "1 roma tomato (diced)", "1 clove garlic (minced)"],
          suitableDiets: ["Vegan", "Gluten-free", "Keto", "Paleo"],
          allergens: ["None"],
          easeOfCooking: "Easy",
        ),
        Recipe(
          name: "Peking Duck",
          cuisineType: "Chinese",
          originLocation: "China",
          imageUrl: "https://redhousespice.com/wp-content/uploads/2021/11/sliced-peking-duck-with-pancakes-1024x1536.jpg",
          recipeUrl: "https://redhousespice.com/peking-duck/",
          ingredientsPerServing: ["1 whole duck (4-5 lbs)", "2 tbsp honey", "2 tbsp soy sauce", "2 tbsp five-spice powder", "1 tbsp white vinegar", "1 tbsp salt", "16 small flour tortillas (or Chinese pancakes)", "1 cucumber (julienned)", "4 green onions (julienned)", "1/4 cup hoisin sauce"],
          suitableDiets: ["None"],
          allergens: ["Gluten", "Soy"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Tacos",
          cuisineType: "Mexican",
          originLocation: "Mexico",
          imageUrl: "https://www.recipetineats.com/wp-content/uploads/2020/09/Ground-Beef-Tacos_8.jpg",
          recipeUrl: "https://www.recipetineats.com/ground-beef-tacos/",
          ingredientsPerServing: ["1 lb ground beef", "1 small onion (chopped)", "2 cloves garlic (minced)", "1 packet taco seasoning", "1/2 cup water", "8 taco shells", "2 cups lettuce (shredded)", "1 cup tomatoes (diced)", "1 cup cheddar cheese (shredded)", "1/2 cup sour cream", "1/4 cup salsa", "1/4 cup guacamole", "2 tbsp cilantro (chopped)"],
          suitableDiets: ["None"],
          allergens: ["Gluten", "Dairy"],
          easeOfCooking: "Easy",
        ),
        Recipe(
          name: "Paella",
          cuisineType: "Spanish",
          originLocation: "Spain",
          imageUrl: "https://www.simplyrecipes.com/thmb/h9RnG3lPtGgXZ2j-OBcBiv-fQH0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Seafood-Paella-LEAD-4-b443710945e04e50886674261ecfb269.jpg",
          recipeUrl: "https://www.simplyrecipes.com/recipes/seafood_paella/",
          ingredientsPerServing: ["2 cups Spanish rice", "4 cups chicken broth", "1/4 cup olive oil", "1 onion (chopped)", "4 cloves garlic (minced)", "1 red bell pepper (sliced)", "1 tsp paprika", "1/2 tsp saffron threads", "1/4 lb chorizo (sliced)", "1/2 lb chicken thighs (cubed)", "1/2 lb shrimp", "1/2 lb mussels", "1/2 cup peas", "1 lemon (cut into wedges)"],
          suitableDiets: ["None"],
          allergens: ["Shellfish", "Gluten"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Moussaka",
          cuisineType: "Greek",
          originLocation: "Greece",
          imageUrl: "https://www.recipetineats.com/wp-content/uploads/2019/03/Greek-Moussaka_3.jpg",
          recipeUrl: "https://www.recipetineats.com/moussaka-greek-eggplant-beef-bake/",
          ingredientsPerServing: ["2 large eggplants (sliced)", "1 lb ground lamb", "1 onion (chopped)", "3 cloves garlic (minced)", "1 can (14oz) crushed tomatoes", "2 tbsp tomato paste", "1 tsp ground cinnamon", "1 tsp dried oregano", "1/2 tsp ground allspice", "1/4 cup red wine", "3 tbsp butter", "3 tbsp all-purpose flour", "2 cups milk", "1/4 tsp ground nutmeg", "2 eggs (beaten)", "1/2 cup Parmesan cheese (grated)"],
          suitableDiets: ["None"],
          allergens: ["Gluten", "Dairy", "Eggs"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Biryani",
          cuisineType: "Indian",
          originLocation: "India",
          imageUrl: "https://www.cubesnjuliennes.com/wp-content/uploads/2020/07/Chicken-Biryani-Recipe-500x500.jpg",
          recipeUrl: "https://www.cubesnjuliennes.com/chicken-biryani-recipe/",
          ingredientsPerServing: ["2 cups basmati rice", "1 lb chicken thighs (cut into pieces)", "1 large onion (sliced)", "3 tomatoes (chopped)", "4 cloves garlic (minced)", "1 tbsp ginger (minced)", "1 tbsp biryani masala", "1 tsp turmeric", "2 green chilies (sliced)", "1/4 cup yogurt", "1/4 cup mint leaves", "1/4 cup cilantro", "3 cups water", "2 bay leaves", "4 cardamom pods", "4 cloves", "1 cinnamon stick", "3 tbsp ghee"],
          suitableDiets: ["Gluten-free"],
          allergens: ["Dairy"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Hamburger",
          cuisineType: "American",
          originLocation: "United States",
          imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=500&q=80",
          recipeUrl: "https://www.seriouseats.com/the-best-burger-recipe",
          ingredientsPerServing: ["1 lb ground beef (80/20)", "1 tsp salt", "1/2 tsp black pepper", "4 hamburger buns", "4 slices American cheese", "4 lettuce leaves", "4 tomato slices", "1/2 red onion (sliced)", "4 tbsp ketchup", "2 tbsp mustard", "4 dill pickle slices", "2 tbsp mayonnaise"],
          suitableDiets: ["None"],
          allergens: ["Gluten", "Dairy"],
          easeOfCooking: "Easy",
        ),
        Recipe(
          name: "Gazpacho",
          cuisineType: "Spanish",
          originLocation: "Spain",
          imageUrl: "https://www.simplyrecipes.com/thmb/dPMTRTJntAj9ZiXnVGceoC9Q-jU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Gazpacho-LEAD-2-72c5d544304149cd99f92428bda2ac11.jpg",
          recipeUrl: "https://www.simplyrecipes.com/recipes/gazpacho/",
          ingredientsPerServing: ["6 ripe tomatoes", "1 cucumber (peeled and chopped)", "1/2 green bell pepper", "1/2 red onion", "2 cloves garlic", "1/4 cup olive oil", "2 tbsp sherry vinegar", "1 tsp salt", "1/2 tsp ground cumin", "2 cups tomato juice", "2 tbsp fresh parsley (chopped)"],
          suitableDiets: ["Vegan", "Gluten-free", "Raw"],
          allergens: ["None"],
          easeOfCooking: "Easy",
        ),
        Recipe(
          name: "Tom Yum Goong",
          cuisineType: "Thai",
          originLocation: "Thailand",
          imageUrl: "https://hot-thai-kitchen.com/wp-content/uploads/2013/05/tom-yum-goong-blog.jpg",
          recipeUrl: "https://hot-thai-kitchen.com/tom-yum-goong/",
          ingredientsPerServing: ["4 cups chicken broth", "1 lb shrimp (peeled and deveined)", "2 stalks lemongrass (bruised)", "5 kaffir lime leaves", "2-inch piece galangal (sliced)", "3 Thai chilies", "1/2 cup mushrooms (sliced)", "3 tbsp fish sauce", "3 tbsp lime juice", "2 tsp sugar", "2 tbsp cilantro (chopped)"],
          suitableDiets: ["Gluten-free", "Dairy-free"],
          allergens: ["Shellfish", "Fish"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Souvlaki",
          cuisineType: "Greek",
          originLocation: "Greece",
          imageUrl: "https://www.recipetineats.com/wp-content/uploads/2019/09/Greek-Chicken-Souvlaki_5.jpg",
          recipeUrl: "https://www.recipetineats.com/greek-chicken-souvlaki-with-tzatziki/",
          ingredientsPerServing: ["1 lb chicken breast (cut into cubes)", "1/4 cup olive oil", "3 tbsp lemon juice", "2 cloves garlic (minced)", "2 tsp dried oregano", "1 tsp dried thyme", "1 tsp salt", "1/2 tsp black pepper", "4 pita breads", "1 cup tzatziki sauce", "1 cucumber (diced)", "1 tomato (diced)", "1/2 red onion (sliced)"],
          suitableDiets: ["None"],
          allergens: ["Gluten", "Dairy"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Feijoada",
          cuisineType: "Brazilian",
          originLocation: "Brazil",
          imageUrl: "https://www.oliviascuisine.com/wp-content/uploads/2019/03/feijoada.jpg",
          recipeUrl: "https://www.oliviascuisine.com/authentic-feijoada-recipe/",
          ingredientsPerServing: ["1 lb dried black beans", "1/2 lb pork shoulder (cubed)", "1/2 lb pork ribs", "1/2 lb smoked sausage (sliced)", "1/4 lb bacon (diced)", "1 onion (chopped)", "4 cloves garlic (minced)", "2 bay leaves", "1 orange (peeled)", "8 cups water", "2 cups cooked white rice", "1/4 cup fresh parsley (chopped)"],
          suitableDiets: ["None"],
          allergens: ["None"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Mole Poblano",
          cuisineType: "Mexican",
          originLocation: "Mexico",
          imageUrl: "https://www.simplyrecipes.com/thmb/-YJqIdXsxE_ngOT3_4zNjp4-d54=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Chicken-Mole-LEAD-4-aaff3ed9ed264a6ea841c062adeda354.jpg",
          recipeUrl: "https://www.simplyrecipes.com/recipes/turkey_mole_poblano/",
          ingredientsPerServing: ["3 dried ancho chiles", "2 dried guajillo chiles", "2 dried chipotle chiles", "1/4 cup sesame seeds", "1/4 cup pumpkin seeds", "1/4 cup almonds", "1 corn tortilla (torn into pieces)", "1 onion (chopped)", "4 cloves garlic", "1 tomato", "1/4 tsp ground cloves", "1/4 tsp ground cinnamon", "1/4 tsp ground coriander", "2 tbsp vegetable oil", "3 oz dark chocolate", "2 cups chicken broth", "2 lbs chicken thighs", "2 tbsp sugar"],
          suitableDiets: ["Gluten-free", "Dairy-free"],
          allergens: ["Nuts"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Couscous",
          cuisineType: "Moroccan",
          originLocation: "Morocco",
          imageUrl: "https://images.unsplash.com/photo-1604329756574-bda1f2cada5d?auto=format&fit=crop&w=500&q=80",
          recipeUrl: "https://www.recipetineats.com/moroccan-couscous/",
          ingredientsPerServing: ["2 cups couscous", "2 cups vegetable broth", "2 tbsp olive oil", "1 onion (chopped)", "2 carrots (diced)", "2 zucchini (diced)", "1 red bell pepper (diced)", "1 can (15oz) chickpeas (drained)", "1 tsp ground cumin", "1 tsp ground coriander", "1/2 tsp ground cinnamon", "1/4 tsp cayenne pepper", "1/4 cup dried apricots (chopped)", "1/4 cup raisins", "1/4 cup fresh mint (chopped)", "1/4 cup fresh parsley (chopped)", "1/4 cup sliced almonds (toasted)"],
          suitableDiets: ["Vegetarian", "Vegan (with vegetable broth)"],
          allergens: ["Gluten", "Nuts"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Baklava",
          cuisineType: "Turkish",
          originLocation: "Turkey",
          imageUrl: "https://images.unsplash.com/photo-1625659156462-bb46dd04081d?auto=format&fit=crop&w=500&q=80",
          recipeUrl: "https://www.thespruceeats.com/baklava-recipe-with-walnuts-and-honey-355033",
          ingredientsPerServing: ["1 lb phyllo dough", "1 lb mixed nuts (walnuts, pistachios, almonds)", "1 cup butter (melted)", "1 tsp ground cinnamon", "1/4 tsp ground cloves", "1 cup water", "1 cup sugar", "1/2 cup honey", "1 strip lemon zest", "1 cinnamon stick"],
          suitableDiets: ["Vegetarian"],
          allergens: ["Gluten", "Dairy", "Nuts"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Sushi Rolls",
          cuisineType: "Japanese",
          originLocation: "Japan",
          imageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=500&q=80",
          recipeUrl: "https://www.justonecookbook.com/sushi-rolls-maki-sushi/",
          ingredientsPerServing: ["2 cups sushi rice (cooked)", "1/4 cup rice vinegar", "2 tbsp sugar", "1/2 tsp salt", "4 sheets nori (seaweed)", "1 cucumber (julienned)", "1 avocado (sliced)", "8 oz sashimi-grade fish (tuna or salmon)", "2 tbsp tobiko (flying fish roe)", "2 tbsp pickled ginger", "2 tbsp wasabi", "1/4 cup soy sauce"],
          suitableDiets: ["Gluten-free"],
          allergens: ["Fish", "Soy"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Beef Stroganoff",
          cuisineType: "Russian",
          originLocation: "Russia",
          imageUrl: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?auto=format&fit=crop&w=500&q=80",
          recipeUrl: "https://natashaskitchen.com/beef-stroganoff/",
          ingredientsPerServing: ["1 lb beef sirloin (sliced thinly)", "2 tbsp butter", "1 onion (sliced)", "8 oz mushrooms (sliced)", "2 tbsp all-purpose flour", "2 cups beef broth", "1 tbsp Dijon mustard", "1/2 cup sour cream", "1/2 tsp salt", "1/4 tsp black pepper", "8 oz egg noodles (cooked)", "2 tbsp fresh parsley (chopped)"],
          suitableDiets: ["None"],
          allergens: ["Gluten", "Dairy", "Eggs"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Jollof Rice",
          cuisineType: "West African",
          originLocation: "Nigeria",
          imageUrl: "https://cheflolaskitchen.com/wp-content/uploads/2018/10/Jollof-Rice-17.jpg",
          recipeUrl: "https://cheflolaskitchen.com/jollof-rice/",
          ingredientsPerServing: ["2 cups long-grain rice", "1 can (14oz) crushed tomatoes", "2 red bell peppers", "2 medium onions", "2 scotch bonnet peppers", "1/4 cup vegetable oil", "2 tbsp tomato paste", "2 tsp curry powder", "1 tsp dried thyme", "2 bay leaves", "1 tsp salt", "3 cups chicken broth", "2 tbsp butter"],
          suitableDiets: ["Gluten-free"],
          allergens: ["Dairy (if using butter)"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Pho Bo",
          cuisineType: "Vietnamese",
          originLocation: "Vietnam",
          imageUrl: "https://www.recipetineats.com/wp-content/uploads/2019/04/Beef-Pho_6.jpg",
          recipeUrl: "https://www.recipetineats.com/vietnamese-pho-recipe/",
          ingredientsPerServing: ["2 lb beef bones", "1 lb beef brisket", "1 onion (halved and charred)", "2-inch piece ginger (charred)", "5 star anise", "1 cinnamon stick", "2 cardamom pods", "2 cloves", "1 tbsp coriander seeds", "2 tbsp fish sauce", "1 tbsp sugar", "1 tsp salt", "8 oz rice noodles", "1/2 lb beef sirloin (thinly sliced)", "1 cup bean sprouts", "1/2 cup Thai basil", "1/2 cup cilantro", "2 limes (cut into wedges)", "2 jalapeños (sliced)"],
          suitableDiets: ["Gluten-free", "Dairy-free"],
          allergens: ["Fish"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Pierogi",
          cuisineType: "Polish",
          originLocation: "Poland",
          imageUrl: "https://www.kingarthurbaking.com/sites/default/files/styles/featured_image/public/2020-02/traditional-cheese-pierogi.jpg",
          recipeUrl: "https://www.kingarthurbaking.com/recipes/homemade-pierogi-recipe",
          ingredientsPerServing: ["2 cups all-purpose flour", "1/2 tsp salt", "1 large egg", "1/2 cup sour cream", "1/4 cup butter (softened)", "1 lb potatoes (peeled and boiled)", "1 cup farmer's cheese", "1 onion (finely chopped)", "2 tbsp butter (for frying)", "1/4 cup sour cream (for serving)"],
          suitableDiets: ["Vegetarian"],
          allergens: ["Gluten", "Dairy", "Eggs"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Bobotie",
          cuisineType: "South African",
          originLocation: "South Africa",
          imageUrl: "https://tasteoftheplace.com/wp-content/uploads/2017/05/Bobotie-taste-of-the-place-recipe-11-rotated.jpg",
          recipeUrl: "https://tasteoftheplace.com/bobotie/",
          ingredientsPerServing: ["2 slices white bread", "1 cup milk", "2 tbsp vegetable oil", "2 onions (chopped)", "2 cloves garlic (minced)", "2 lbs ground beef", "2 tbsp curry powder", "1 tsp dried herbs", "2 tbsp chutney", "2 tbsp apricot jam", "2 tbsp lemon juice", "1/4 cup raisins", "1/4 cup almonds (chopped)", "3 eggs", "1/2 tsp turmeric", "6 bay leaves"],
          suitableDiets: ["None"],
          allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Empanadas",
          cuisineType: "Argentinian",
          originLocation: "Argentina",
          imageUrl: "https://www.laylita.com/recipes/wp-content/uploads/2008/02/Empanadas-mendocinas-1024x682.jpg",
          recipeUrl: "https://www.laylita.com/recipes/beef-empanadas/",
          ingredientsPerServing: ["3 cups all-purpose flour", "1 tsp salt", "1/2 cup cold butter (cubed)", "1 egg", "1/4 cup cold water", "1 lb ground beef", "2 onions (finely diced)", "1 red bell pepper (diced)", "3 cloves garlic (minced)", "2 tsp cumin", "1 tsp paprika", "1/2 tsp red pepper flakes", "1/2 cup green olives (chopped)", "1/4 cup raisins", "3 hard-boiled eggs (chopped)", "1 egg (beaten, for brushing)"],
          suitableDiets: ["None"],
          allergens: ["Gluten", "Dairy", "Eggs"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Haggis",
          cuisineType: "Scottish",
          originLocation: "Scotland",
          imageUrl: "https://food-images.files.bbci.co.uk/food/recipes/haggis_75658_16x9.jpg",
          recipeUrl: "https://www.bbcgoodfood.com/recipes/haggis",
          ingredientsPerServing: ["1 sheep's stomach or large sausage casing", "1 lb sheep's pluck (heart, liver, lungs)", "1 lb ground beef suet", "2 onions (finely chopped)", "2 cups oatmeal", "1 tsp salt", "1 tsp black pepper", "1/2 tsp nutmeg", "1/2 tsp mixed spice", "2 cups beef stock", "2 lbs potatoes (for mashed potatoes side)", "2 lbs turnips (for mashed turnips side)"],
          suitableDiets: ["None"],
          allergens: ["Gluten"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Goulash",
          cuisineType: "Hungarian",
          originLocation: "Hungary",
          imageUrl: "https://www.daringgourmet.com/wp-content/uploads/2014/03/Goulash-2-xc.jpg",
          recipeUrl: "https://www.daringgourmet.com/traditional-hungarian-goulash-gulyas/",
          ingredientsPerServing: ["2 lbs beef chuck (cubed)", "2 tbsp lard or butter", "2 large onions (chopped)", "2 cloves garlic (minced)", "2 tbsp Hungarian sweet paprika", "1 tsp caraway seeds", "2 bell peppers (chopped)", "2 tomatoes (chopped)", "2 carrots (sliced)", "2 potatoes (cubed)", "6 cups beef broth", "1 bay leaf", "1 tsp salt", "1/2 tsp black pepper", "1/4 cup fresh parsley (chopped)"],
          suitableDiets: ["Gluten-free"],
          allergens: ["Dairy (if using butter)"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Injera with Doro Wat",
          cuisineType: "Ethiopian",
          originLocation: "Ethiopia",
          imageUrl: "https://www.daringgourmet.com/wp-content/uploads/2013/08/Doro-Wat-8.jpg",
          recipeUrl: "https://www.daringgourmet.com/doro-wat-spicy-ethiopian-chicken-stew/",
          ingredientsPerServing: ["2 cups teff flour", "2 cups water", "1/2 tsp salt (for injera)", "2 lbs chicken thighs", "3 tbsp niter kibbeh (Ethiopian spiced butter)", "2 large onions (finely chopped)", "3 tbsp berbere spice blend", "2 tbsp tomato paste", "4 cloves garlic (minced)", "1-inch piece ginger (grated)", "1 cup chicken broth", "4 hard-boiled eggs", "1 lemon (juiced)", "1/2 tsp salt (for doro wat)"],
          suitableDiets: ["Dairy-free (without niter kibbeh)"],
          allergens: ["Eggs", "Dairy (if using regular butter)"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Borscht",
          cuisineType: "Ukrainian",
          originLocation: "Ukraine",
          imageUrl: "https://natashaskitchen.com/wp-content/uploads/2022/02/Borscht-Recipe-5.jpg",
          recipeUrl: "https://natashaskitchen.com/borscht-recipe-with-meat/",
          ingredientsPerServing: ["1 lb beef (chuck or sirloin, cubed)", "8 cups beef broth", "1 large onion (chopped)", "2 large carrots (julienned)", "2 large beets (peeled and grated)", "2 potatoes (diced)", "1/2 cabbage (shredded)", "2 tbsp tomato paste", "1 tbsp vegetable oil", "2 bay leaves", "1 tbsp white vinegar", "2 cloves garlic (minced)", "1 tsp sugar", "1/2 tsp salt", "1/4 tsp black pepper", "Sour cream for serving", "Fresh dill for garnish"],
          suitableDiets: ["Gluten-free"],
          allergens: ["Dairy (if using sour cream)"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Poutine",
          cuisineType: "Canadian",
          originLocation: "Canada",
          imageUrl: "https://www.seasonsandsuppers.ca/wp-content/uploads/2014/01/new-poutine-1.jpg",
          recipeUrl: "https://www.seasonsandsuppers.ca/authentic-canadian-poutine-recipe/",
          ingredientsPerServing: ["2 lbs russet potatoes", "2 tbsp vegetable oil", "1 cup cheese curds", "2 cups beef gravy", "1/4 tsp salt", "1/4 tsp black pepper", "2 tbsp fresh parsley (chopped)"],
          suitableDiets: ["Vegetarian (with vegetable gravy)"],
          allergens: ["Dairy"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Ceviche",
          cuisineType: "Peruvian",
          originLocation: "Peru",
          imageUrl: "https://www.simplyrecipes.com/thmb/F71Ir3QjurHqEF7PvY_k0ioIZdY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Ceviche-LEAD-2-89f8a4792f444c22ae0b98fff8b365f8.jpg",
          recipeUrl: "https://www.simplyrecipes.com/recipes/ceviche/",
          ingredientsPerServing: ["1 lb fresh white fish (sea bass, halibut, or tilapia)", "1 cup lime juice", "1/2 red onion (thinly sliced)", "1 cup chopped cilantro", "1 jalapeño (seeded and minced)", "1 cup diced cucumber", "1 avocado (diced)", "1 tbsp olive oil", "1/2 tsp salt", "1/4 tsp black pepper", "Tortilla chips for serving"],
          suitableDiets: ["Gluten-free", "Dairy-free"],
          allergens: ["Fish"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Kimchi Jjigae",
          cuisineType: "Korean",
          originLocation: "South Korea",
          imageUrl: "https://www.koreanbapsang.com/wp-content/uploads/2019/11/DSC_0152-3.jpg",
          recipeUrl: "https://www.koreanbapsang.com/kimchi-jjigae-kimchi-stew/",
          ingredientsPerServing: ["2 cups kimchi (chopped)", "1/2 lb pork belly (sliced)", "1 block tofu (cubed)", "3 cups anchovy broth or water", "1 tbsp gochugaru (Korean red pepper flakes)", "1 tbsp gochujang (Korean red pepper paste)", "2 tsp sesame oil", "2 green onions (chopped)", "2 cloves garlic (minced)", "1 tsp sugar", "1 tsp salt", "2 cups cooked rice (for serving)"],
          suitableDiets: ["Gluten-free"],
          allergens: ["Fish", "Soy"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Shakshuka",
          cuisineType: "Middle Eastern",
          originLocation: "Tunisia/Israel",
          imageUrl: "https://downshiftology.com/wp-content/uploads/2018/12/Shakshuka-19.jpg",
          recipeUrl: "https://downshiftology.com/recipes/shakshuka/",
          ingredientsPerServing: ["1 large onion (diced)", "1 red bell pepper (diced)", "4 cloves garlic (minced)", "2 tsp paprika", "1 tsp cumin", "1/4 tsp chili powder", "1 can (28oz) whole peeled tomatoes", "6 large eggs", "1/2 cup feta cheese (crumbled)", "2 tbsp fresh parsley (chopped)", "1 tbsp olive oil", "1/2 tsp salt", "1/4 tsp black pepper", "Pita bread for serving"],
          suitableDiets: ["Vegetarian", "Gluten-free (without pita)"],
          allergens: ["Eggs", "Dairy"],
          easeOfCooking: "Easy",
        ),
        Recipe(
          name: "Chicken Adobo",
          cuisineType: "Filipino",
          originLocation: "Philippines",
          imageUrl: "https://www.kawalingpinoy.com/wp-content/uploads/2013/04/filipino-chicken-adobo-7.jpg",
          recipeUrl: "https://www.kawalingpinoy.com/chicken-adobo/",
          ingredientsPerServing: ["2 lbs chicken thighs", "1/3 cup soy sauce", "1/3 cup white vinegar", "8 cloves garlic (crushed)", "1 bay leaf", "1 tsp black peppercorns", "2 tbsp vegetable oil", "1 cup water", "2 green onions (chopped)", "2 cups cooked white rice (for serving)"],
          suitableDiets: ["Gluten-free (with GF soy sauce)", "Dairy-free"],
          allergens: ["Soy"],
          easeOfCooking: "Easy",
        ),
        Recipe(
          name: "Köttbullar (Swedish Meatballs)",
          cuisineType: "Swedish",
          originLocation: "Sweden",
          imageUrl: "https://hips.hearstapps.com/hmg-prod/images/swedish-meatballs-index-640775a2a2e5b.jpg",
          recipeUrl: "https://www.delish.com/cooking/recipe-ideas/a35459221/swedish-meatballs-recipe/",
          ingredientsPerServing: ["1 lb ground beef", "1/2 lb ground pork", "1/2 cup breadcrumbs", "1/4 cup milk", "1 small onion (finely diced)", "1 egg", "1/4 tsp ground allspice", "1/4 tsp ground nutmeg", "1/2 tsp salt", "1/4 tsp black pepper", "2 tbsp butter", "2 tbsp flour", "2 cups beef broth", "1/2 cup heavy cream", "1 tbsp lingonberry jam", "Mashed potatoes (for serving)"],
          suitableDiets: ["None"],
          allergens: ["Gluten", "Dairy", "Eggs"],
          easeOfCooking: "Medium",
        ),
        Recipe(
          name: "Tabbouleh",
          cuisineType: "Lebanese",
          originLocation: "Lebanon",
          imageUrl: "https://feelgoodfoodie.net/wp-content/uploads/2019/05/Authentic-Lebanese-Tabbouleh-Salad-Recipe-12.jpg",
          recipeUrl: "https://feelgoodfoodie.net/recipe/authentic-lebanese-tabbouleh-salad/",
          ingredientsPerServing: ["1/2 cup fine bulgur wheat", "4 bunches fresh parsley (finely chopped)", "1 bunch fresh mint (finely chopped)", "4 green onions (finely chopped)", "4 tomatoes (diced)", "1 cucumber (diced)", "1/4 cup olive oil", "1/4 cup lemon juice", "1 tsp salt", "1/2 tsp black pepper", "Romaine lettuce leaves (for serving)"],
          suitableDiets: ["Vegan", "Vegetarian", "Dairy-free"],
          allergens: ["Gluten"],
          easeOfCooking: "Easy",
        ),
        Recipe(
          name: "Pavlova",
          cuisineType: "Australian/New Zealand",
          originLocation: "Australia/New Zealand",
          imageUrl: "https://preppykitchen.com/wp-content/uploads/2019/04/Pavlova-new.jpg",
          recipeUrl: "https://preppykitchen.com/pavlova/",
          ingredientsPerServing: ["4 egg whites (room temperature)", "1 cup granulated sugar", "1 tsp vanilla extract", "1 tsp white vinegar", "2 tsp cornstarch", "1 cup heavy cream (whipped)", "2 cups mixed fresh fruits (strawberries, kiwi, passion fruit, berries)", "2 tbsp powdered sugar", "1 tbsp fresh mint leaves (for garnish)"],
          suitableDiets: ["Vegetarian", "Gluten-free"],
          allergens: ["Eggs", "Dairy"],
          easeOfCooking: "Hard",
        ),
        Recipe(
          name: "Peri Peri Chicken",
          cuisineType: "African Portuguese",
          originLocation: "Mozambique/Portugal",
          imageUrl: "https://www.africanbites.com/wp-content/uploads/2018/04/IMG_0301.jpg",
          recipeUrl: "https://www.africanbites.com/peri-peri-chicken/",
          ingredientsPerServing: ["1 whole chicken (cut into pieces)", "6 red chili peppers", "6 cloves garlic", "1 red bell pepper", "1 onion", "1/4 cup olive oil", "2 tbsp paprika", "1 tbsp oregano", "2 bay leaves", "1/4 cup lemon juice", "1 tsp salt", "1/2 tsp black pepper", "1/4 cup fresh cilantro", "Lemon wedges (for serving)"],
          suitableDiets: ["Gluten-free", "Dairy-free"],
          allergens: ["None"],
          easeOfCooking: "Medium",
        ),
      ];
      
      return recipes;
    } catch (e) {
      print('Error loading recipes: $e');
      return [];
    }
  }
  
  /// Parse a CSV line, handling quoted values correctly
  List<String> _parseCSVLine(String line) {
    final List<String> result = [];
    bool inQuotes = false;
    String currentValue = '';
    
    for (int i = 0; i < line.length; i++) {
      final String char = line[i];
      
      if (char == '"') {
        inQuotes = !inQuotes;
      } else if (char == ',' && !inQuotes) {
        result.add(_cleanQuotes(currentValue));
        currentValue = '';
      } else {
        currentValue += char;
      }
    }
    
    // Add the last value
    if (currentValue.isNotEmpty) {
      result.add(_cleanQuotes(currentValue));
    }
    
    return result;
  }
  
  /// Remove quotes from a value
  String _cleanQuotes(String value) {
    return value.trim().replaceAll('"', '');
  }
  
  /// Get a list of unique cuisine types
  Future<List<String>> getUniqueCuisineTypes() async {
    final List<Recipe> recipes = await loadRecipes();
    final Set<String> cuisineTypes = recipes.map((recipe) => recipe.cuisineType).toSet();
    final List<String> sortedCuisineTypes = cuisineTypes.toList()..sort();
    return sortedCuisineTypes;
  }
  
  /// Filter recipes by cuisine type
  Future<List<Recipe>> getRecipesByCuisineType(String cuisineType) async {
    final List<Recipe> allRecipes = await loadRecipes();
    return allRecipes.where((recipe) => recipe.cuisineType == cuisineType).toList();
  }
}
